NWEB.Practice.T03.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NWEB.Practice.T03.Core;
using NWEB.Practice.T03.Core.Entity;
using NWEB.Practice.T03.DataAccessLayer.IRepository;
using System.Security.Claims;

namespace NWEB.Practice.T03.Web.Controllers
{
    [Authorize(Roles = SD.ROLE_ADMIN)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWord;
        public CategoryController(IUnitOfWork categoryRepository)
        {
            _unitOfWord = categoryRepository;
        }

        public IActionResult Index()
        {
            List<Category> categories = _unitOfWord.Category.GetAll().ToList();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWord.Category.Add(category);
                _unitOfWord.SaveChange();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Category? category = _unitOfWord.Category.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWord.Category.Update(category);
                _unitOfWord.SaveChange();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Delete(Guid? id)
        {
            Category? category = _unitOfWord.Category.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            _unitOfWord.Category.Delete(category);
            _unitOfWord.SaveChange();
            return RedirectToAction("Index");
        }
    }
}

NWEB.Practice.T03.Web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NWEB.Practice.T03.Core.Entity;
using NWEB.Practice.T03.DataAccessLayer.IRepository;
using NWEB.Practice.T03.DataAccessLayer.Repository;

namespace NWEB.Practice.T03.Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IUnitOfWork _unitOfWord;
        public CustomerController(IUnitOfWork categoryRepository)
        {
            _unitOfWord = categoryRepository;
        }
        public IActionResult Index(Guid? id)
        {
            List<Flower> flowers = null;
            if (id == null)
            {
                flowers = _unitOfWord.Flower.GetAll().ToList();
            }
            else
            {
                flowers = _unitOfWord.Flower.GetFlowerByCategory(id);
            }
            IEnumerable<SelectListItem> categoryLists = _unitOfWord.Category.GetAll().Select(u => new SelectListItem
            {
                Text = u.CategoryName,
                Value = u.Id.ToString(),
            }
            );
            ViewBag.categoryList = categoryLists;
            return View(flowers);
        }
        public IActionResult Search()
        {
            return View();
        }

        public IActionResult AddToCart()
        {
            TempData["success"] = "The flower is added to cart successfully";
            return RedirectToAction("Index");
        }
    }
}

NWEB.Practice.T03.Web/Controllers/FlowerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NWEB.Practice.T03.Core;
using NWEB.Practice.T03.Core.Entity;
using NWEB.Practice.T03.DataAccessLayer.IRepository;
using NWEB.Practice.T03.DataAccessLayer.Repository;
using System.Security.Claims;

namespace NWEB.Practice.T03.Web.Controllers
{
    [Authorize(Roles = SD.ROLE_ADMIN)]
    public class FlowerController : Controller
    {
        private readonly IUnitOfWork _unitOfWord;
        public FlowerController(IUnitOfWork categoryRepository)
        {
            _unitOfWord = categoryRepository;
        }

        public IActionResult Index()
        {
            List<Flower> flowers = _unitOfWord.Flower.GetAllWithCategory().ToList();
            return View(flowers);
        }

        public IActionResult Create()
        {
            IEnumerable<SelectListItem> categories = _unitOfWord.Category.GetAll().Select(u => new SelectListItem
            {
                Text = u.CategoryName,
                Value = u.Id.ToString(),
            }
            );
            ViewBag.Category = categories;
            return View();
        }

        [HttpPost]
        public IActionResult Create(Flower flower)
        {
            if (ModelState.IsValid)
            {
                _unitOfWord.Flower.Add(flower);
                _unitOfWord.SaveChange();
                return RedirectToAction("Index");
            }
            IEnumerable<SelectListItem> categories = _unitOfWord.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.CategoryName,
                    Value = u.Id.ToString(),
                }
            );
            ViewBag.Category = categories;
            return View(flower);
        }

        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Flower? flower = _unitOfWord.Flower.Find(id);
            if (flower == null)
            {
                return NotFound();
            }
            IEnumerable<SelectListItem> categories = _unitOfWord.Category.GetAll().Select(u => new SelectListItem
            {
                Text = u.CategoryName,
                Value = u.Id.ToString(),
            }
);
            ViewBag.Category = categories;
            return View(flower);
        }

        [HttpPost]
        public IActionResult Edit(Flower flower)
        {
            if (ModelState.IsValid)
            {
                _unitOfWord.Flower.Update(flower);
                _unitOfWord.SaveChange();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(Guid? id)
        {
            Flower? flower = _unitOfWord.Flower.Find(id);
            if (flower == null)
            {
                return NotFound();
            }
            _unitOfWord.Flower.Delete(flower);
            _unitOfWord.SaveChange();
            return RedirectToAction("Index");
        }
    }
}

NWEB.Practice.T03.Web/Controllers/SaleOffController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NWEB.Practice.T03.Core;
using NWEB.Practice.T03.Core.Entity;
using NWEB.Practice.T03.DataAccessLayer.IRepository;

namespace NWEB.Practice.T03.Web.Controllers
{
    [Authorize(Roles = SD.ROLE_ADMIN)]
    public class SaleOffController : Controller
    {
        private readonly IUnitOfWork _unitOfWord;
        public SaleOffController(IUnitOfWork categoryRepository)
        {
            _unitOfWord = categoryRepository;
        }
        public IActionResult Index()
        {
            IEnumerable<SelectListItem> categories = _unitOfWord.Category.GetAll().Select(u => new SelectListItem
            {
                Text = u.CategoryName,
                Value = u.Id.ToString(),
            }
            );
            ViewBag.Category = categories;
            return View();
        }
        [HttpPost]
        public IActionResult Index(Guid? flowerId, decimal saleOff)
        {
            Flower flow = _unitOfWord.Flower.Find(flowerId);
            flow.SalePrice = flow.Price - (flow.Price * saleOff / 100);
            _unitOfWord.Flower.Update(flow);
            _unitOfWord.SaveChange();
            return View();
        }

        public JsonResult OnGetGetProducts(Guid? categoryId)
        {
            var products = _unitOfWord.Flower.GetFlowerByCategory(categoryId);
            IEnumerable<SelectListItem> result = products.Select(u => new SelectListItem
            {
                Text = u.FlowerName,
                Value = u.Id.ToString(),
            }
            );
            return new JsonResult(result);
        }
    }
}

NWEB.Practice.T03.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NWEB.Practice.T03.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NWEB.Practice.T03.Web.styles.css" asp-append-version="true" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NWEB.Practice.T03.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category Manage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flower" asp-action="Index">Flower Manage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SaleOff" asp-action="Index">Sale Manage</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NWEB.Practice.T03.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NWEB.Practice.T03.Web/Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NWEB.Practice.T03.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NWEB.Practice.T03.Web.styles.css" asp-append-version="true" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://kit.fontawesome.com/81e4fcabce.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Customer" asp-action="Index">Flower Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" asp-area="" asp-controller="Category" asp-action="Index">Corporate</a>
                                <ul class="dropdown-menu">
                                    @foreach (var category in ViewBag.categoryList)
                                    {
                                        <a class="dropdown-item" asp-controller="Customer" asp-action="Index" asp-route-id="@category.Value">@category.Text</a>
                                    }
                                </ul>
                            </div>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="">Love &zz Romance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="">Sympathy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="">New Baby</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Search">Search Flower</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NWEB.Practice.T03.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NWEB.Practice.T03.Web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        toastr.error('@TempData["error"]');
    </script>
}